mysql:
  dsn: nanollm:REPLACE_ME@tcp(127.0.0.1:3306)/nanollm
  # detail_retain: 1000
admin:
  username: admin
  password: REPLACE_ME
api_keys:
  - name: default
    value: sk-REPLACE_ME
models:
  - name: gpt-4o
    providers:
      - name: openai
        url: https://api.openai.com/v1/chat/completions
        model: gpt-4o
        headers:
          Authorization: Bearer sk-REPLACE_ME
      - name: openrouter
        url: https://openrouter.ai/api/v1/chat/completions
        model: openai/gpt-4o
        headers:
          Authorization: Bearer sk-or-REPLACE_ME
  - name: fast
    providers:
      - name: ollama
        url: http://127.0.0.1:11434/v1/chat/completions
        model: llama3.1
        headers:
          Authorization: Bearer ollama
